; NOTE: Assertions have been autogenerated by utils/update_llubi_test_checks.py UTC_ARGS: --version 6
; RUN: not llubi --verbose < %s 2>&1 | FileCheck %s

define void @main() {
  %a = alloca [4 x [2147483648 x [2147483648 x i8]]], align 8
  %v = load [4 x [2147483648 x [2147483648 x i8]]], ptr %a
  ret void
}
; CHECK: [2147483648 x i8] is too large!
; CHECK-NEXT:   %v = load [4 x [2147483648 x [2147483648 x i8]]], ptr %a, align 1 at @main <stdin>:6
; CHECK-NEXT: error: -: input module cannot be executed!
