; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=instcombine -S < %s | FileCheck %s

; This vscale udiv with a power-of-2 spalt on the rhs should not crash opt

define <vscale x 2 x i32> @udiv_pow2_vscale(<vscale x 2 x i32> %lhs) {
; CHECK-LABEL: define <vscale x 2 x i32> @udiv_pow2_vscale(
; CHECK-SAME: <vscale x 2 x i32> [[LHS:%.*]]) {
; CHECK-NEXT:    [[RES1:%.*]] = lshr <vscale x 2 x i32> [[LHS]], shufflevector (<vscale x 2 x i32> insertelement (<vscale x 2 x i32> poison, i32 1, i64 0), <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer)
; CHECK-NEXT:    ret <vscale x 2 x i32> [[RES1]]
;
  %splatter = insertelement <vscale x 2 x i32> undef, i32 2, i32 0
  %rhs = shufflevector <vscale x 2 x i32> %splatter,
  <vscale x 2 x i32> undef,
  <vscale x 2 x i32> zeroinitializer
  %res = udiv <vscale x 2 x i32> %lhs, %rhs
  ret <vscale x 2 x i32> %res
}

; This fixed width udiv with a power-of-2 splat on the rhs should also not
; crash, and instcombine should eliminate the udiv

; CHECK-LABEL: define <2 x i32> @udiv_pow2_fixed(<2 x i32> %lhs)
; CHECK-NOT: udiv
define <2 x i32> @udiv_pow2_fixed(<2 x i32> %lhs) {
  %splatter = insertelement <2 x i32> undef, i32 2, i32 0
  %rhs = shufflevector <2 x i32> %splatter,
  <2 x i32> undef,
  <2 x i32> zeroinitializer
  %res = udiv <2 x i32> %lhs, %rhs
  ret <2 x i32> %res
}
