# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# RUN: llvm-mca -mtriple=riscv64 -mcpu=xiangshan-nanhu -timeline -iterations=1 -register-file-stats < %s | FileCheck %s

# Test move elimination
mv a1, a0
mv a2, a1
mv a3, a2
mv a4, a3
mv a5, a4
mv a6, a5
mv a7, a6
add a0, a7, a7
fmv.s fa1, fa0
fmv.s fa2, fa1
fadd.s fa0, fa2, fa2
fmv.d fa1, fa0
fmv.d fa2, fa1
fadd.d fa0, fa2, fa2

# CHECK:      Iterations:        1
# CHECK-NEXT: Instructions:      14
# CHECK-NEXT: Total Cycles:      10
# CHECK-NEXT: Total uOps:        14

# CHECK:      Dispatch Width:    6
# CHECK-NEXT: uOps Per Cycle:    1.40
# CHECK-NEXT: IPC:               1.40
# CHECK-NEXT: Block RThroughput: 2.3

# CHECK:      Instruction Info:
# CHECK-NEXT: [1]: #uOps
# CHECK-NEXT: [2]: Latency
# CHECK-NEXT: [3]: RThroughput
# CHECK-NEXT: [4]: MayLoad
# CHECK-NEXT: [5]: MayStore
# CHECK-NEXT: [6]: HasSideEffects (U)

# CHECK:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# CHECK-NEXT:  1      1     0.25                        mv	a1, a0
# CHECK-NEXT:  1      1     0.25                        mv	a2, a1
# CHECK-NEXT:  1      1     0.25                        mv	a3, a2
# CHECK-NEXT:  1      1     0.25                        mv	a4, a3
# CHECK-NEXT:  1      1     0.25                        mv	a5, a4
# CHECK-NEXT:  1      1     0.25                        mv	a6, a5
# CHECK-NEXT:  1      1     0.25                        mv	a7, a6
# CHECK-NEXT:  1      1     0.25                        add	a0, a7, a7
# CHECK-NEXT:  1      3     0.25                        fmv.s	fa1, fa0
# CHECK-NEXT:  1      3     0.25                        fmv.s	fa2, fa1
# CHECK-NEXT:  1      3     0.25                        fadd.s	fa0, fa2, fa2
# CHECK-NEXT:  1      3     0.25                        fmv.d	fa1, fa0
# CHECK-NEXT:  1      3     0.25                        fmv.d	fa2, fa1
# CHECK-NEXT:  1      3     0.25                        fadd.d	fa0, fa2, fa2

# CHECK:      Register File statistics:
# CHECK-NEXT: Total number of mappings created:    3
# CHECK-NEXT: Max number of mappings used:         3

# CHECK:      *  Register File #1 -- XS2FpuPRF:
# CHECK-NEXT:    Number of physical registers:     192
# CHECK-NEXT:    Total number of mappings created: 2
# CHECK-NEXT:    Max number of mappings used:      2
# CHECK-NEXT:    Number of optimizable moves:      4
# CHECK-NEXT:    Number of moves eliminated:       4  (100.0%)
# CHECK-NEXT:    Number of zero moves:             0  (0.0%)
# CHECK-NEXT:    Max moves eliminated per cycle:   3

# CHECK:      *  Register File #2 -- XS2IntegerPRF:
# CHECK-NEXT:    Number of physical registers:     192
# CHECK-NEXT:    Total number of mappings created: 1
# CHECK-NEXT:    Max number of mappings used:      1
# CHECK-NEXT:    Number of optimizable moves:      7
# CHECK-NEXT:    Number of moves eliminated:       7  (100.0%)
# CHECK-NEXT:    Number of zero moves:             0  (0.0%)
# CHECK-NEXT:    Max moves eliminated per cycle:   6

# CHECK:      Resources:
# CHECK-NEXT: [0.0] - XS2ALU
# CHECK-NEXT: [0.1] - XS2ALU
# CHECK-NEXT: [0.2] - XS2ALU
# CHECK-NEXT: [0.3] - XS2ALU
# CHECK-NEXT: [1.0] - XS2FMAC
# CHECK-NEXT: [1.1] - XS2FMAC
# CHECK-NEXT: [1.2] - XS2FMAC
# CHECK-NEXT: [1.3] - XS2FMAC
# CHECK-NEXT: [2.0] - XS2FMISC
# CHECK-NEXT: [2.1] - XS2FMISC
# CHECK-NEXT: [3.0] - XS2LD
# CHECK-NEXT: [3.1] - XS2LD
# CHECK-NEXT: [4.0] - XS2MDU
# CHECK-NEXT: [4.1] - XS2MDU
# CHECK-NEXT: [5]   - XS2MISC
# CHECK-NEXT: [6.0] - XS2ST
# CHECK-NEXT: [6.1] - XS2ST

# CHECK:      Resource pressure per iteration:
# CHECK-NEXT: [0.0]  [0.1]  [0.2]  [0.3]  [1.0]  [1.1]  [1.2]  [1.3]  [2.0]  [2.1]  [3.0]  [3.1]  [4.0]  [4.1]  [5]    [6.0]  [6.1]
# CHECK-NEXT:  -      -      -     1.00    -      -     1.00   1.00    -      -      -      -      -      -      -      -      -

# CHECK:      Resource pressure by instruction:
# CHECK-NEXT: [0.0]  [0.1]  [0.2]  [0.3]  [1.0]  [1.1]  [1.2]  [1.3]  [2.0]  [2.1]  [3.0]  [3.1]  [4.0]  [4.1]  [5]    [6.0]  [6.1]  Instructions:
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     mv	a1, a0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     mv	a2, a1
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     mv	a3, a2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     mv	a4, a3
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     mv	a5, a4
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     mv	a6, a5
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     mv	a7, a6
# CHECK-NEXT:  -      -      -     1.00    -      -      -      -      -      -      -      -      -      -      -      -      -     add	a0, a7, a7
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     fmv.s	fa1, fa0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     fmv.s	fa2, fa1
# CHECK-NEXT:  -      -      -      -      -      -      -     1.00    -      -      -      -      -      -      -      -      -     fadd.s	fa0, fa2, fa2
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     fmv.d	fa1, fa0
# CHECK-NEXT:  -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -      -     fmv.d	fa2, fa1
# CHECK-NEXT:  -      -      -      -      -      -     1.00    -      -      -      -      -      -      -      -      -      -     fadd.d	fa0, fa2, fa2

# CHECK:      Timeline view:
# CHECK-NEXT: Index     0123456789

# CHECK:      [0,0]     DR   .   .   mv	a1, a0
# CHECK-NEXT: [0,1]     DR   .   .   mv	a2, a1
# CHECK-NEXT: [0,2]     DR   .   .   mv	a3, a2
# CHECK-NEXT: [0,3]     DR   .   .   mv	a4, a3
# CHECK-NEXT: [0,4]     DR   .   .   mv	a5, a4
# CHECK-NEXT: [0,5]     DR   .   .   mv	a6, a5
# CHECK-NEXT: [0,6]     .DR  .   .   mv	a7, a6
# CHECK-NEXT: [0,7]     .DeER.   .   add	a0, a7, a7
# CHECK-NEXT: [0,8]     .D--R.   .   fmv.s	fa1, fa0
# CHECK-NEXT: [0,9]     .D--R.   .   fmv.s	fa2, fa1
# CHECK-NEXT: [0,10]    .DeeeER  .   fadd.s	fa0, fa2, fa2
# CHECK-NEXT: [0,11]    .D----R  .   fmv.d	fa1, fa0
# CHECK-NEXT: [0,12]    . D---R  .   fmv.d	fa2, fa1
# CHECK-NEXT: [0,13]    . D==eeeER   fadd.d	fa0, fa2, fa2

# CHECK:      Average Wait times (based on the timeline view):
# CHECK-NEXT: [0]: Executions
# CHECK-NEXT: [1]: Average time spent waiting in a scheduler's queue
# CHECK-NEXT: [2]: Average time spent waiting in a scheduler's queue while ready
# CHECK-NEXT: [3]: Average time elapsed from WB until retire stage

# CHECK:            [0]    [1]    [2]    [3]
# CHECK-NEXT: 0.     1     0.0    0.0    0.0       mv	a1, a0
# CHECK-NEXT: 1.     1     0.0    0.0    0.0       mv	a2, a1
# CHECK-NEXT: 2.     1     0.0    0.0    0.0       mv	a3, a2
# CHECK-NEXT: 3.     1     0.0    0.0    0.0       mv	a4, a3
# CHECK-NEXT: 4.     1     0.0    0.0    0.0       mv	a5, a4
# CHECK-NEXT: 5.     1     0.0    0.0    0.0       mv	a6, a5
# CHECK-NEXT: 6.     1     0.0    0.0    0.0       mv	a7, a6
# CHECK-NEXT: 7.     1     1.0    1.0    0.0       add	a0, a7, a7
# CHECK-NEXT: 8.     1     0.0    0.0    2.0       fmv.s	fa1, fa0
# CHECK-NEXT: 9.     1     0.0    0.0    2.0       fmv.s	fa2, fa1
# CHECK-NEXT: 10.    1     1.0    1.0    0.0       fadd.s	fa0, fa2, fa2
# CHECK-NEXT: 11.    1     0.0    0.0    4.0       fmv.d	fa1, fa0
# CHECK-NEXT: 12.    1     0.0    0.0    3.0       fmv.d	fa2, fa1
# CHECK-NEXT: 13.    1     3.0    0.0    0.0       fadd.d	fa0, fa2, fa2
# CHECK-NEXT:        1     0.4    0.1    0.8       <total>
