// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -std=c23 -O1 -emit-llvm -o - %s | FileCheck %s

typedef unsigned long long uintptr_t;
int *ptr_int;
// CHECK-LABEL: define dso_local i64 @test_int(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i64 0
//
uintptr_t test_int() {
  return (uintptr_t)ptr_int & 3;
}
struct foo { alignas(64) int x[32]; } *ptr_struct_alignas;
// CHECK-LABEL: define dso_local i64 @test_struct_alignas(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i64 0
//
uintptr_t test_struct_alignas() {
  return (uintptr_t)ptr_struct_alignas & 63;
}
typedef double __attribute__((aligned(64))) aligned_double;
aligned_double *ptr_aligned_typedef;
// CHECK-LABEL: define dso_local i64 @test_aligned_typedef(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i64 0
//
uintptr_t test_aligned_typedef() {
  return (uintptr_t)ptr_aligned_typedef & 63;
}
void *ptr_void;
// CHECK-LABEL: define dso_local i64 @test_void(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @ptr_void, align 8, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
// CHECK-NEXT:    [[AND:%.*]] = and i64 [[TMP1]], 1
// CHECK-NEXT:    ret i64 [[AND]]
//
uintptr_t test_void() {
  return (uintptr_t)ptr_void & 1;
}
void (*ptr_func)();
// CHECK-LABEL: define dso_local i64 @test_func(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i64 0
//
uintptr_t test_func() {
  return (uintptr_t)ptr_func & 3;
}
//.
// CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// CHECK: [[META3]] = !{!"any pointer", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK: [[META5]] = !{!"Simple C/C++ TBAA"}
//.
